### ISSUE TITLE
Bug: requestHeartbeatNow called with 1 arg but SDK defines () => void — TSC error on main

### ISSUE THREAD

**Issue by csuzngjh** [csuzngjh/principles#310]
## Bug Description

`evolution-worker.ts:2229` calls `api.runtime.system.requestHeartbeatNow({ reason: "..." })` with one argument, but the SDK type declaration defines `requestHeartbeatNow: () => void` (zero arguments).

This was introduced in PR #305 (fix/pain-diagnosis-hung) when `runHeartbeatOnce` was replaced with `requestHeartbeatNow`.

## Evidence

```bash
$ npx tsc --noEmit -p packages/openclaw-plugin/tsconfig.json 2>&1 | grep requestHeartbeatNow
src/service/evolution-worker.ts(2229,64): error TS2554: Expected 0 arguments, but got 1.
```

```ts
// evolution-worker.ts:2229 — calls with argument
api.runtime.system.requestHeartbeatNow({
    reason: `pd-pain-diagnosis: pain flag detected, starting diagnostician`,
});

// openclaw-sdk.d.ts:119 — defines with 0 args
requestHeartbeatNow: () => void;
```

## Impact

- TSC error on main (1 error)
- Runtime: the argument is silently ignored (JS does not enforce arity). The heartbeat IS triggered, but the `reason` string is lost — no debuggability impact from the heartbeat itself, but the reason will not appear in heartbeat logs
- The previous `runHeartbeatOnce({ reason })` signature accepted an options object, but `requestHeartbeatNow` was designed with a simpler API

## Root Cause

API signature mismatch between plugin code and SDK type declaration. PR #305 migrated from `runHeartbeatOnce` to `requestHeartbeatNow` but carried over the `{ reason }` argument pattern.

## Fix Suggestions

1. **Remove the argument** — `api.runtime.system.requestHeartbeatNow()` (match the SDK signature)
2. **Update the SDK** — change to `requestHeartbeatNow: (opts?: { reason?: string }) => void` if the runtime supports it

Option 1 is the minimal fix. The reason can be logged before the call instead.

**Comment by csuzngjh** [comment]
Verified: requestHeartbeatNow SDK signature updated to accept optional opts parameter. TSC --noEmit reports 0 errors. Closing as resolved.
